Repository GSG-K3/code-academy-wiki, pull requests merged in 2020-05, with the labels that each got.

#104 Student Profile Page
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/LayoutComponents/Home/Home.css
  client/src/LayoutComponents/Home/Home.js
  client/src/LayoutComponents/StudentProfile/StudentProfile.css
  client/src/LayoutComponents/StudentProfile/StudentProfile.js
  client/src/SharedComponents/Footer/Footer.css
  client/src/SharedComponents/NavBar/NavBar.css
  client/src/SharedComponents/ProjectView/ProjectView.css
  client/src/SharedComponents/Slideshow/Slideshow.css
  client/src/SharedComponents/Slideshow/Slideshow.js
  client/src/SharedComponents/StudentCard/StudentCard.css
  client/src/SharedComponents/StudentCard/StudentCard.js
  client/src/SharedComponents/navbar.svg
  client/src/images/contact-icons/email.svg
  client/src/images/contact-icons/github.svg
  client/src/images/contact-icons/house.svg
  client/src/images/contact-icons/phone.svg
  package.json
  server/controllers/allStudents.js
  server/controllers/index.js
  server/controllers/student.js
  server/database/queries/getAllStudents.js
  server/database/queries/getStudent.js
  server/index.js
Labels: T1d, back-end, front-end, in-progress

#122 Getproject
  client/src/App.css
  client/src/App.js
  client/src/LayoutComponents/ProjectDetails/ProjectDetails.css
  client/src/LayoutComponents/ProjectDetails/ProjectDetails.js
  client/src/LayoutComponents/ProjectDetails/index.js
  client/src/SharedComponents/ProjectView/ProjectView.css
  client/src/SharedComponents/ProjectView/ProjectView.js
  client/src/images/github.svg
  client/src/images/pc.svg
  package.json
  server/app.js
  server/controllers/getProject.js
  server/controllers/index.js
  server/database/queries/getProject.js
  server/index.js
Labels: DONE, back-end, front-end

#133 fix dummy data
  server/app.js
  server/controllers/index.js
  server/database/config/dummy_data.sql
Labels: DONE

#135 Getproject
  client/src/LayoutComponents/ProjectDetails/ProjectDetails.css
  client/src/LayoutComponents/ProjectDetails/ProjectDetails.js
  server/database/queries/getProject.js
Labels: in-progress

#107 Cohorts
  client/src/App.js
  client/src/LayoutComponents/Cohorts/Cohorts.css
  client/src/LayoutComponents/Cohorts/Cohorts.js
  client/src/LayoutComponents/Cohorts/index.js
  client/src/LayoutComponents/Home/Home.js
  client/src/SharedComponents/CohortCard/CohortCard.js
  server/controllers/cohorts.js
  server/controllers/getCohortsByCity.js
  server/controllers/index.js
  server/database/config/db_build.sql
  server/database/queries/getCohortByCity.js
  server/database/queries/getCohorts.js
  server/database/queries/getProject.js
Labels: DONE, back-end, front-end

#150 Fix and refactor nav bar
  client/src/SharedComponents/NavBar/NavBar.css
  client/src/SharedComponents/NavBar/NavBar.js
Labels: DONE, front-end, refactor
