Repository GSG-K3/code-academy-wiki, pull requests merged in 2020-04, with the labels that each got.

#56 adding front end folders #35
  client/.gitignore
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
Labels: in-progress

#55 set up server files
  .gitignore
  client/package.json
  package.json
  server/app.js
  server/controllers/index.js
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/database/config/dummy_data.sql
  server/database/queries/getAllStudents.js
  server/index.js
Labels: in-progress

#57 Update README.md #3
  README.md
Labels: in-progress

#61 initiate database files with dummy data #38
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/database/config/dummy_data.sql
  server/database/queries/getAllStudents.js
Labels: in-progress

#69 remove react logos from manifest file
  client/public/manifest.json
Labels: DONE

#70 create slideshow using dummy data
  client/src/SharedComponent/Slideshow/Slideshow.css
  client/src/SharedComponent/Slideshow/Slideshow.js
  client/src/SharedComponent/Slideshow/index.js
  client/src/images/adele.jpeg
  package.json
Labels: DONE, front-end

#82 Nav bar
  client/src/App.js
  client/src/SharedComponents/NavBar/NavBar.css
  client/src/SharedComponents/NavBar/NavBar.js
  client/src/SharedComponents/NavBar/navbar.svg
  client/src/SharedComponents/Slideshow/Slideshow.css
  client/src/SharedComponents/Slideshow/Slideshow.js
  client/src/SharedComponents/Slideshow/index.js
  client/src/SharedComponents/StudentCard/StudentCard.css
  client/src/SharedComponents/StudentCard/StudentCard.js
  client/src/SharedComponents/StudentCard/index.js
Labels: shared component

#85 Fix nav bar
  client/src/App.css
  client/src/SharedComponents/NavBar/NavBar.css
  client/src/SharedComponents/NavBar/NavBar.js
  client/src/SharedComponents/NavBar/index.js
  client/src/SharedComponents/navbar.svg
  client/src/images/logo.png
  client/src/images/logo.svg
  client/src/images/nav-container.svg
  client/src/images/navbar.svg
Labels: fixing, in-progress
